// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: XXXAAA.proto

package XXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XXXAAAClient is the client API for XXXAAA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XXXAAAClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xXXAAAClient struct {
	cc grpc.ClientConnInterface
}

func NewXXXAAAClient(cc grpc.ClientConnInterface) XXXAAAClient {
	return &xXXAAAClient{cc}
}

func (c *xXXAAAClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XXX.XXX.XXXAAA/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XXXAAAServer is the server API for XXXAAA service.
// All implementations must embed UnimplementedXXXAAAServer
// for forward compatibility
type XXXAAAServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXXXAAAServer()
}

// UnimplementedXXXAAAServer must be embedded to have forward compatible implementations.
type UnimplementedXXXAAAServer struct {
}

func (UnimplementedXXXAAAServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXXXAAAServer) mustEmbedUnimplementedXXXAAAServer() {}

// UnsafeXXXAAAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XXXAAAServer will
// result in compilation errors.
type UnsafeXXXAAAServer interface {
	mustEmbedUnimplementedXXXAAAServer()
}

func RegisterXXXAAAServer(s grpc.ServiceRegistrar, srv XXXAAAServer) {
	s.RegisterService(&XXXAAA_ServiceDesc, srv)
}

func _XXXAAA_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XXXAAAServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXX.XXX.XXXAAA/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XXXAAAServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XXXAAA_ServiceDesc is the grpc.ServiceDesc for XXXAAA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XXXAAA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XXX.XXX.XXXAAA",
	HandlerType: (*XXXAAAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XXXAAA_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XXXAAA.proto",
}
